import type { Config } from 'tailwindcss'

export default <Config>{
  darkMode: 'class',
  content: [
    './app/**/*.{vue,js,ts,jsx,tsx}',
    './app/components/**/*.{vue,js,ts}',
    './app/layouts/**/*.{vue,js,ts}',
    './app/pages/**/*.{vue,js,ts}',
    './app/composables/**/*.{js,ts}',
    './app/plugins/**/*.{js,ts}',
    './app/app.{js,ts,vue}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#4648d4',
        'primary-container': '#6063ee',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'secondary': '#6b38d4',
        'secondary-container': '#8455ef',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d0bcff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'tertiary': '#904900',
        'tertiary-container': '#b55d00',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#ffb783',
        'surface': '#fcf8ff',
        'surface-bright': '#fcf8ff',
        'surface-dim': '#dbd8e4',
        'surface-container': '#efecf8',
        'surface-container-low': '#f5f2fe',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e9e6f3',
        'surface-container-highest': '#e4e1ed',
        'surface-variant': '#e4e1ed',
        'on-surface': '#1b1b23',
        'on-surface-variant': '#464554',
        'on-background': '#1b1b23',
        'outline': '#767586',
        'outline-variant': '#c7c4d7',
        'background': '#FAFAFB',
        'muted': '#6B7280',
        'suami': '#3B82F6',
        'istri': '#EC4899',
        'gabungan': '#8B5CF6',
        'income': '#10B981',
        'expense': '#F43F5E',
        'warning': '#F59E0B',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'inverse-surface': '#303038',
        'inverse-on-surface': '#f2effb',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', '-apple-system', 'sans-serif'],
        'display-balance': ['Plus Jakarta Sans', 'sans-serif'],
        'tabular-number': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-base': ['Plus Jakarta Sans', 'sans-serif'],
        'metadata-xs': ['Plus Jakarta Sans', 'sans-serif'],
      },
      spacing: {
        'margin-page': '1rem',
        'stack-lg': '1.5rem',
        'stack-md': '1rem',
        'stack-sm': '0.5rem',
        'gutter-grid': '1rem',
      },
      boxShadow: {
        '2xs': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        'xs': '0 1px 3px 0 rgba(0, 0, 0, 0.07), 0 1px 2px -1px rgba(0, 0, 0, 0.07)',
      },
    },
  },
}
